# Generated by Django 4.1.7 on 2023-04-06 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
                ('intrest1', models.TextField()),
                ('intrest2', models.TextField()),
                ('intrest3', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('trending', models.BooleanField(blank=True, null=True)),
                ('editorspick', models.BooleanField(blank=True, null=True)),
                ('center', models.BooleanField(blank=True, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('ytswitch', models.BooleanField(blank=True, default=False, null=True)),
                ('ytlink', models.TextField(blank=True, null=True)),
                ('credit0', models.CharField(blank=True, max_length=100, null=True)),
                ('h1', models.CharField(blank=True, max_length=200, null=True)),
                ('p1', models.TextField(blank=True, null=True)),
                ('qt1', models.TextField(blank=True, null=True)),
                ('pic1', models.TextField(blank=True, null=True)),
                ('credit1', models.CharField(blank=True, max_length=100, null=True)),
                ('h2', models.CharField(blank=True, max_length=200, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('qt2', models.TextField(blank=True, null=True)),
                ('pic2', models.TextField(blank=True, null=True)),
                ('credit2', models.CharField(blank=True, max_length=100, null=True)),
                ('h3', models.CharField(blank=True, max_length=200, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('qt3', models.TextField(blank=True, null=True)),
                ('pic3', models.TextField(blank=True, null=True)),
                ('credit3', models.CharField(blank=True, max_length=100, null=True)),
                ('h4', models.CharField(blank=True, max_length=200, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
                ('qt4', models.TextField(blank=True, null=True)),
                ('pic4', models.TextField(blank=True, null=True)),
                ('credit4', models.CharField(blank=True, max_length=100, null=True)),
                ('h5', models.CharField(blank=True, max_length=200, null=True)),
                ('p5', models.TextField(blank=True, null=True)),
                ('qt5', models.TextField(blank=True, null=True)),
                ('pic5', models.TextField(blank=True, null=True)),
                ('credit5', models.CharField(blank=True, max_length=100, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('slug', models.SlugField(max_length=200)),
                ('next', models.TextField(blank=True, null=True)),
                ('timetoread', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
