# Generated by Django 4.1.7 on 2023-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='intrest1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='intrest2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='intrest3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
